version: '3'

services:
  db:
    container_name: logdb-db
    user: 1000:1000
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
    networks:
      - logdb

  backend:
    container_name: logdb-backend
    user: 1000:1000
    build:
      context: ./backend
    volumes:
      - ./backend:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DEBUG=false
    networks:
      - logdb
    depends_on:
      - db

  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/www/data
    ports:
      - 8080:80
    networks:
      - logdb
    depends_on:
      - backend

networks:
  logdb:
    driver: bridge