# Generated by Django 4.0.2 on 2022-02-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pretty_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pretty_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField(null=True)),
                ('stdout', models.TextField(null=True)),
                ('stderr', models.TextField(null=True)),
                ('severity', models.PositiveSmallIntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.host')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.sender')),
                ('tags', models.ManyToManyField(blank=True, to='logs.Tag')),
            ],
        ),
    ]
